name: Deploy Website with CodeDeploy

on:
  workflow_dispatch:
    inputs:
      application-name:
        description: 'AWS CodeDeploy application name'
        required: true
        type: string
      deployment-group:
        description: 'AWS CodeDeploy deployment group name'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip source code
        run: |
          zip -r website.zip index.html scripts appspec.yml

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%s)
          S3_KEY=website-$TIMESTAMP.zip
          aws s3 cp website.zip s3://$S3_BUCKET/$S3_KEY
          echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "${{ inputs.application-name }}" \
            --deployment-group-name "${{ inputs.deployment-group }}" \
            --s3-location bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region $AWS_REGION
